spring.application.name=training-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/training_backend
spring.datasource.username=Nourcine
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

springdoc.swagger-ui.persistAuthorization=true
server.port=8080
